#!/bin/sh

source ./env.sh
. /etc/profile.d/xcat.sh

########## add hack sulotion of rocky os support #######
cd ${package_dir}
tar -xvzf backup_xcat_hack.tgz
cd backup_xcat_hack
cp -r install /opt/xcat/share/xcat/install/rocky 
cp -r netboot /opt/xcat/share/xcat/netboot/rocky 
/bin/cp ./discinfo.pm /opt/xcat/lib/perl/xCAT/data/discinfo.pm 
/bin/cp ./imgcapture.pm /opt/xcat/lib/perl/xCAT_plugin/imgcapture.pm 
/bin/cp ./imgport.pm /opt/xcat/lib/perl/xCAT_plugin/imgport.pm 
/bin/cp ./anaconda.pm /opt/xcat/lib/perl/xCAT_plugin/anaconda.pm 
/bin/cp ./geninitrd.pm /opt/xcat/lib/perl/xCAT_plugin/geninitrd.pm 
/bin/cp ./route.pm /opt/xcat/lib/perl/xCAT_plugin/route.pm 
/bin/cp ./Postage.pm /opt/xcat/lib/perl/xCAT/Postage.pm 
/bin/cp ./Utils.pm /opt/xcat/lib/perl/xCAT/Utils.pm 
/bin/cp ./ProfiledNodeUtils.pm /opt/xcat/lib/perl/xCAT/ProfiledNodeUtils.pm 
/bin/cp ./SvrUtils.pm /opt/xcat/lib/perl/xCAT/SvrUtils.pm 
/bin/cp ./Template.pm /opt/xcat/lib/perl/xCAT/Template.pm 
/bin/cp ./Schema.pm /opt/xcat/lib/perl/xCAT/Schema.pm 
systemctl restart xcatd
cd ~
#########################################################

chtab key=system passwd.username=root passwd.password=`openssl rand -base64 12`

#### Install ClusterShell
yum -y install clustershell
# Setup node definitions
cd /etc/clustershell/groups.d
cat local.cfg > local.cfg.orig
echo "adm: ${sms_name}" > local.cfg
echo "compute: ${compute_prefix}0[1-3]" >> local.cfg   ####need to be modified
echo "all: @adm,@compute" >> local.cfg
cd ~
######

# Update memlock settings on master
perl -pi -e 's/# End of file/\* soft memlock unlimited\n$&/s' /etc/security/limits.conf
perl -pi -e 's/# End of file/\* hard memlock unlimited\n$&/s' /etc/security/limits.conf

# Disable /tftpboot and /install export entries
perl -pi -e "s|/tftpboot|#/tftpboot|" /etc/exports
perl -pi -e "s|/install|#/install|" /etc/exports
### note: fsid should be uniq, if add dir###
echo "/home *(rw,no_subtree_check,fsid=10,no_root_squash)" >> /etc/exports
echo "/opt/ohpc/pub *(ro,no_subtree_check,fsid=11)" >> /etc/exports
##echo "/opt/repo *(ro,no_subtree_check,fsid=12)" >> /etc/exports
exportfs -a
systemctl restart nfs-server
systemctl enable nfs-server


#####################         ###############################
## add nis server 
yum install -y rpcbind yp-tools ypbind ypserv 
systemctl enable rpcbind ypserv ypxfrd yppasswdd
##ypdomainname   ${domain_name}
echo "NISDOMAIN=${domain_name}" >> /etc/sysconfig/network

echo "# generated by /sbin/dhclient-script" >/etc/yp.conf
echo "domain ${domain_name} server ${sms_ip}" >>/etc/yp.conf

###
authconfig --update --enablenis 

systemctl restart rpcbind ypserv ypxfrd yppasswdd
### update nis database 
/usr/lib64/yp/ypinit -m
###  ctrl-d to continue